import BlogList from "@/components/blogs/blog-list";
import type { Metadata } from "next";
import prisma from "@/database";


export const metadata: Metadata = {
  title: "博客 | Huala Blog",
  description: "Generated by create next app",
};


const Blogs = async () => {
  // 获取所有博客信息
  const getAllList: Blog[] = await prisma.post.findMany();
  return <BlogList lists={getAllList} />;
}

export default Blogs;