import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./global.css";
import NextAuthProvider from "@/providers/next-auth-provider";
import NextThemeProvider from "@/providers/theme-provider";
import GlobalState from "@/context";
import Header from "@/components/header";
import { Toaster } from "@/components/ui/toaster"

const poppins = Poppins({
  weight: ['300', '400', '500', '600'],
  subsets: ['latin'],
  display: 'swap'
})

export const metadata: Metadata = {
  title: "首页 | Huala Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        <NextThemeProvider attribute="class" defaultTheme="system" enableSystem
          disableTransitionOnChange>
          <NextAuthProvider>
            <GlobalState>
              <Header />
              {children}
            </GlobalState>
          </NextAuthProvider>
        </NextThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
