import { PostList } from "@/components/posts";
import prisma from "@/lib/prisma";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "博客 | Huala Post",
  description: "Generated by create next app",
};


const Blogs = async () => {
  // 获取所有博客信息
  const getAllList: Post[] = await prisma.post.findMany();
  return <PostList lists={getAllList} />;
}

export default Blogs;